#!/bin/sh
sudo -v

echo "Installing packages..."
sudo pikaur -S i3-gaps lightdm lightdm-mini-greeter termite chromium dmenu zsh oh-my-zsh-git ttf-iosevka wpgtk-git feh neofetch thunar scrot compton polybar jsoncpp dunst neovim python-neovim node npm

echo "Copying lightdm config to /etc/lightdm..."
sudo rm /etc/lightdm/lightdm.conf /etc/lightdm/lightdm-mini-greeter.conf
sudo cp ~/.config/etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf
sudo cp ~/.config/etc/lightdm/lightdm-mini-greeter.conf /etc/lightdm/lightdm-mini-greeter.conf

echo "Setting up oh-my-zsh..."
sudo chsh justinian -s /bin/zsh
sudo cp -r /usr/share/oh-my-zsh/* ~/.oh-my-zsh
sudo chown justinian:justinian -R .oh-my-zsh

echo "Downloading wpg templates..."
wpg-install.sh -gi

echo "Installing VimPlug..."
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

